### ISSUE TITLE
Course #1

### ISSUE THREAD

**Issue by nicolasmendonca** [nicolasmendonca/mars#1]
## 💡 Course Ideas

- Building a youtube clone with sveltekit and Supabase.
- Building a udemy clone with sveltekit and Supabase.
- Sveltekit from scratch
- Sveltekit for React Developers
- Cypress: Ship JS Apps with confidence

## 📆 Deadline

**31 November 2022**

## 🥇 Primary Goals

- [ ] Produce a course with the knowledge I already have
- [ ] No matter if it's cringy, as long as it provides free value to students
- [ ] Deliver at least 10 videos with educational content

## 🥈 Secondary Goals

- [ ] Find a way to make the content easier to engage
  - Voice over pre-recorded code screen? Sounds good for youtube but not for Udemy
 
## 🚗 Milestones

- [ ] Determine course content by ⏳ September 5th
- [ ] Write a list of concepts people should learn from this course. ⏳ September 12th
- [ ] Record course
- [ ] Edit it
- [ ] Review concept list and make sure all topics are covered.
- [ ] Publish it for free on Youtube ⏳ November 31th
- [ ] Create Tik Tok content to promote it
